### PR TITLE
add instructions for Windows

### PR DESCRIPTION
**Pull request by ShaneSmiskol**
Not the most ideal way to flash NEOS, but without installing a lot of extra software (eg. img2simg), this works perfectly.

### CODE REVIEW

**Comment by robbederks** [comment]
Could somebody automate these instructions in a .bat file (other than downloading the adb stuff I guess)? Would be easier than having to do all this manually.
Also, the download.py script should work on windows too I think. This also adds the extra safety of checking the hashes before trying to flash the image.

**Comment by illumiN8i** [comment]
download.py doesn't work on windows due to creating the symlink on this line: https://github.com/commaai/eon-neos/blob/master/download.py#L28

**Comment by roxasthenobody98** [comment]
download.py works in Windows Subsystem for Linux.

**Comment by pd0wm** [comment]
It should now work on Windows.

**Pull request closed without merging**
